name: Sync to Apps
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Template Repository
        uses: actions/checkout@v4
        with: 
          path: main

      - name: Checkout App 1
        uses: actions/checkout@v4
        with:
          repository: Youssef548/app1
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: app1

      - name: Checkout App 2
        uses: actions/checkout@v4
        with:
          repository: Youssef548/app2
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: app2

      - name: List files
        run: tree --gitignore

      - name: Copy Changes
        run: |
          rsync -av --exclude '.git' --exclude '.github' main/ app1/
          rsync -av --exclude '.git' --exclude '.github' main/ app2/

      - name: Set up Git user
        run: |
          git config --global user.email "youssefahmedpvp@gmail.com"
          git config --global user.name "Youssef548"

      - name: Commit and Push Changes to Apps
        run: |
          for app in app1 app2; do
            cd $GITHUB_WORKSPACE/$app
            if [[ -n "$(git status --porcelain)" ]]; then
              git add .
              git commit -m "Sync from template: $(date +%Y-%m-%d)"
              git push origin main || echo "Failed to push to $app"
            else
              echo "No changes to sync for $app"
            fi
          done